import { DocumentTemplate, TemplateFamily } from '../types';

export const INITIAL_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'tpl-appointment',
    code: 'LOA-001',
    family: 'Letter of Appointment',
    title: 'Standard Letter of Appointment',
    description: 'Formal offer and appointment letter for new executive/non-executive employees with essential terms.',
    jurisdiction: 'All',
    riskLevel: 'Medium',
    version: '2.0.1',
    legalBasis: 'Employment Act 1955 (Peninsular) / Sarawak Labour Ordinance Cap. 76',
    lastReviewed: '2026-06-15',
    clauses: [
      {
        id: 'c-app-1',
        title: '1. Position & Reporting Structure',
        category: 'Appointment',
        content: 'The Company is pleased to offer you the position of [JOB_TITLE] in the [DEPARTMENT] Department, reporting directly to [REPORTING_MANAGER]. Your employment shall commence on [START_DATE].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-app-2',
        title: '2. Remuneration & Benefits',
        category: 'Compensation',
        content: 'Your basic monthly salary shall be RM [BASIC_SALARY] payable in arrears on or before the last working day of each calendar month. In addition, you shall be entitled to fixed monthly allowances of RM [FIXED_ALLOWANCES]. Statutory contributions to EPF, SOCSO, and EIS will be made in accordance with Malaysian statutory requirements.',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-app-3',
        title: '3. Probationary Period & Notice',
        category: 'Probation',
        content: 'You shall serve a probationary period of [PROBATION_MONTHS] months from your commencement date. During probation, either party may terminate this contract by providing [NOTICE_PERIOD_PROBATION] weeks written notice or salary in lieu thereof. Upon satisfactory completion, written confirmation will be issued.',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-app-4',
        title: '4. Working Hours & Location',
        category: 'Hours',
        content: 'Your regular work hours shall be 8:30 AM to 5:30 PM, Monday through Friday, at our office located at [WORK_LOCATION_ADDRESS]. Total regular hours shall not exceed 45 hours per week in accordance with applicable labor regulations.',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-app-5',
        title: '5. Confidentiality & Fidelity',
        category: 'Conduct',
        content: 'You shall maintain strict confidentiality regarding all company trade secrets, customer data, and financial affairs during and after your employment. You shall devote your full time and attention to the Company and shall not engage in outside business activities without prior written consent.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-cos',
    code: 'COS-002',
    family: 'Contract of Service',
    title: 'Comprehensive Contract of Service',
    description: 'Detailed formal contract of service covering all statutory baseline terms for Peninsular & Sarawak.',
    jurisdiction: 'All',
    riskLevel: 'Medium',
    version: '2.1.0',
    legalBasis: 'Employment Act 1955 Amendment 2022 / Sarawak Labour Ordinance',
    lastReviewed: '2026-07-01',
    clauses: [
      {
        id: 'c-cos-1',
        title: '1. Employment Scope & Jurisdiction',
        category: 'General',
        content: 'This Contract of Service is governed by the laws of Malaysia and specifically applicable under the jurisdiction of [JURISDICTION]. The Employee agrees to perform duties as [JOB_TITLE].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-cos-2',
        title: '2. Working Hours, Rest Days & Overtime',
        category: 'Work Conditions',
        content: 'Normal working hours shall not exceed 8 hours per day or 45 hours in any one week. Employees eligible for overtime shall be compensated at 1.5x normal hourly rate for work beyond normal hours, 2.0x for work on rest days, and 3.0x on gazetted public holidays.',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-cos-3',
        title: '3. Statutory Leave Entitlements',
        category: 'Leaves',
        content: 'Annual leave entitlement: [ANNUAL_LEAVE_DAYS] days per annum. Sick leave entitlement: [SICK_LEAVE_DAYS] days per annum (or 60 days if hospitalization is required). Paid maternity leave of 98 days and paid paternity leave of 7 consecutive days shall apply per statutory regulations.',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-cos-4',
        title: '4. Termination & Notice Period',
        category: 'Termination',
        content: 'Post-confirmation notice period required for termination by either party shall be [NOTICE_PERIOD_CONFIRMED] weeks (or 4 weeks if served <2 years, 6 weeks if 2-5 years, 8 weeks if >5 years as per statutory baseline).',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-part-time',
    code: 'PTA-003',
    family: 'Part-Time Employment Agreement',
    title: 'Part-Time Employment Agreement',
    description: 'Specific terms for hourly/part-time employees compliant with Employment (Part-Time Employees) Regulations.',
    jurisdiction: 'All',
    riskLevel: 'Medium',
    version: '1.4.0',
    legalBasis: 'Employment (Part-Time Employees) Regulations 2010',
    lastReviewed: '2026-05-20',
    clauses: [
      {
        id: 'c-pt-1',
        title: '1. Part-Time Terms & Hourly Rate',
        category: 'Remuneration',
        content: 'The Employee is engaged as a Part-Time Employee at an hourly rate of RM [HOURLY_RATE]. Weekly hours shall be [WEEKLY_HOURS] hours (between 30% and 70% of full-time normal hours).',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-pt-2',
        title: '2. Overtime & Rest Day Pro-Rata',
        category: 'Overtime',
        content: 'Work performed beyond agreed daily part-time hours up to normal full-time daily hours shall be paid at normal hourly rate. Work exceeding full-time daily hours shall be paid at 1.5x hourly rate.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-confirmation',
    code: 'CONF-004',
    family: 'Confirmation & Probation Documents',
    title: 'Employee Confirmation Letter',
    description: 'Official notice confirming employment upon successful completion of probation.',
    jurisdiction: 'All',
    riskLevel: 'Low',
    version: '1.2.0',
    legalBasis: 'Malaysian Common Law & EA Guidelines',
    lastReviewed: '2026-06-10',
    clauses: [
      {
        id: 'c-conf-1',
        title: '1. Confirmation Announcement',
        category: 'Confirmation',
        content: 'We are pleased to inform you that upon evaluation of your performance during your probationary period, you have been officially confirmed in your position as [JOB_TITLE] with effect from [CONFIRMATION_DATE].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-conf-2',
        title: '2. Salary Adjustment / Terms Review',
        category: 'Terms',
        content: 'Consequent to your confirmation, your monthly basic salary shall be adjusted to RM [CONFIRMED_SALARY] per month. All other terms and conditions of your original Letter of Appointment shall remain in full force.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-change-addendum',
    code: 'CHANGE-005',
    family: 'Employment Change Documents',
    title: 'Employment Terms Addendum / Salary Adjustment',
    description: 'Addendum modifying salary, designation, or working conditions while maintaining continuity.',
    jurisdiction: 'All',
    riskLevel: 'Medium',
    version: '2.0.0',
    legalBasis: 'Contract Law / Employment Continuity Rules',
    lastReviewed: '2026-06-28',
    clauses: [
      {
        id: 'c-chg-1',
        title: '1. Variation of Contract Terms',
        category: 'Variation',
        content: 'This Addendum supplements your original contract dated [ORIGINAL_CONTRACT_DATE]. Effective from [EFFECTIVE_DATE], the following variations are hereby agreed: Designation: [NEW_JOB_TITLE], Basic Monthly Salary: RM [NEW_BASIC_SALARY].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-chg-2',
        title: '2. Mutual Acceptance',
        category: 'Agreement',
        content: 'All other terms and conditions not specifically amended herein shall remain unchanged. Both parties confirm voluntary acceptance of these revised terms.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-pip',
    code: 'PIP-006',
    family: 'Performance Improvement Plan',
    title: 'Performance Improvement Plan (PIP)',
    description: 'Structured 30/60/90-day PIP document setting clear expectations, goals, and review milestones.',
    jurisdiction: 'All',
    riskLevel: 'Medium',
    version: '1.5.0',
    legalBasis: 'Industrial Court Guidelines on Performance Management',
    lastReviewed: '2026-07-05',
    clauses: [
      {
        id: 'c-pip-1',
        title: '1. Identification of Performance Deficiencies',
        category: 'Deficiencies',
        content: 'This Performance Improvement Plan (PIP) addresses specific performance gaps observed in your role as [JOB_TITLE], including: [PERFORMANCE_DEFICIENCIES_LIST].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-pip-2',
        title: '2. Objectives & Measurable Milestones',
        category: 'Targets',
        content: 'During the [PIP_DURATION_DAYS]-day evaluation period commencing [PIP_START_DATE] to [PIP_END_DATE], you are required to achieve the following targets: [MEASURABLE_TARGETS]. Weekly progress reviews will be conducted with [REPORTING_MANAGER].',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-memo',
    code: 'MEMO-007',
    family: 'HR Memo / Employee Notice',
    title: 'General HR Staff Memo & Policy Notice',
    description: 'Official company communication for company policies, attendance reminders, MC rules, and holiday notices.',
    jurisdiction: 'All',
    riskLevel: 'Low',
    version: '1.1.0',
    legalBasis: 'Internal Company Directives',
    lastReviewed: '2026-05-10',
    clauses: [
      {
        id: 'c-memo-1',
        title: '1. Memo Directive',
        category: 'Directive',
        content: 'TO: All Staff / [DEPARTMENT]\nSUBJECT: [MEMO_SUBJECT]\nDATE: [MEMO_DATE]\n\nPlease be advised that effective [EFFECTIVE_DATE], the company hereby issues the following directive regarding [MEMO_TOPIC]: [MEMO_BODY]. Compliance is mandatory.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-showcause',
    code: 'SC-008',
    family: 'Show Cause Letter',
    title: 'Show Cause Letter (Disciplinary Misconduct)',
    description: 'Formal written request for employee explanation regarding alleged misconduct before disciplinary action.',
    jurisdiction: 'All',
    riskLevel: 'Medium',
    version: '2.2.0',
    legalBasis: 'Natural Justice Principle (Audi Alteram Partem)',
    lastReviewed: '2026-07-12',
    clauses: [
      {
        id: 'c-sc-1',
        title: '1. Allegations of Misconduct',
        category: 'Allegation',
        content: 'It has been reported that on or around [INCIDENT_DATE] at approximately [INCIDENT_TIME] at [INCIDENT_LOCATION], you allegedly committed the following act of misconduct: [DETAILED_ALLEGATIONS_FACTS].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-sc-2',
        title: '2. Opportunity to Show Cause',
        category: 'Right of Reply',
        content: 'You are hereby requested to show cause in writing as to why disciplinary action should not be taken against you. Your written explanation must reach HR no later than [REPLY_DEADLINE_DATE] at 5:00 PM.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-case-closure',
    code: 'CLOS-009',
    family: 'Case Closure Letter',
    title: 'Disciplinary Case Closure Notice',
    description: 'Official notice recording case outcome (satisfactory reply, exoneration, or NFA).',
    jurisdiction: 'All',
    riskLevel: 'Medium',
    version: '1.0.0',
    legalBasis: 'Industrial Relations Act Guidelines',
    lastReviewed: '2026-06-01',
    clauses: [
      {
        id: 'c-clos-1',
        title: '1. Case Conclusion Record',
        category: 'Conclusion',
        content: 'With reference to the Show Cause Letter dated [SHOW_CAUSE_DATE] and your written reply dated [REPLY_DATE], the Management has thoroughly reviewed your explanation. We hereby inform you that your reply is deemed satisfactory, and Case [CASE_NUMBER] is officially CLOSED with No Further Action.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-warning',
    code: 'WARN-010',
    family: 'Warning Letter Family',
    title: 'Written Warning Letter (1st / 2nd / Final)',
    description: 'Formal disciplinary warning letter issued following investigation or unsatisfactory show cause reply.',
    jurisdiction: 'All',
    riskLevel: 'High',
    version: '2.1.0',
    legalBasis: 'Section 14 Employment Act 1955 / Industrial Court Principles',
    lastReviewed: '2026-07-10',
    clauses: [
      {
        id: 'c-warn-1',
        title: '1. Disciplinary Finding',
        category: 'Finding',
        content: 'Further to the Show Cause Letter issued on [SHOW_CAUSE_DATE] and your explanation dated [REPLY_DATE], the Management finds your explanation unsatisfactory regarding [ALLEGATION_SUMMARY].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-warn-2',
        title: '2. Issuance of Warning & Required Correction',
        category: 'Penalty',
        content: 'Consequently, the Management hereby issues this [WARNING_TYPE] (Written Warning). You are sternly advised to rectify your conduct immediately. Failure to improve or repetition of misconduct may result in further severe disciplinary action up to dismissal.',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-di-notice',
    code: 'DI-011',
    family: 'Notice of Domestic Inquiry',
    title: 'Notice of Domestic Inquiry (Inquiry Panel)',
    description: 'Formal notice directing employee to attend a Domestic Inquiry hearing with panel details and rights.',
    jurisdiction: 'All',
    riskLevel: 'High',
    version: '2.0.0',
    legalBasis: 'Due Process Section 14(1) Employment Act 1955',
    lastReviewed: '2026-07-15',
    clauses: [
      {
        id: 'c-di-1',
        title: '1. Notice to Attend Domestic Inquiry',
        category: 'Notice',
        content: 'You are hereby directed to attend a formal Domestic Inquiry hearing to be held on [DI_DATE] at [DI_TIME] at [DI_VENUE]. The Inquiry Panel shall investigate the following formal charges: [FORMAL_CHARGES_LIST].',
        status: 'BBH Standard',
        isMandatory: true,
      },
      {
        id: 'c-di-2',
        title: '2. Rights of Defense & Witnesses',
        category: 'Rights',
        content: 'You have the right to attend the inquiry, cross-examine company witnesses, present your own witnesses and documentary evidence, and be assisted by a fellow employee from the company. Please notify HR of your witnesses by [WITNESS_DEADLINE_DATE].',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
  {
    id: 'tpl-ack',
    code: 'ACK-012',
    family: 'Employee Acknowledgement Documents',
    title: 'Handbook / Document Receipt Acknowledgement',
    description: 'Formal receipt and acknowledgement signed by employee confirming receipt and understanding of policies.',
    jurisdiction: 'All',
    riskLevel: 'Low',
    version: '1.1.0',
    legalBasis: 'Internal Policy Record & Evidentiary Proof',
    lastReviewed: '2026-04-18',
    clauses: [
      {
        id: 'c-ack-1',
        title: '1. Confirmation of Receipt',
        category: 'Acknowledgement',
        content: 'I, [EMPLOYEE_NAME] (NRIC: [NRIC]), hereby confirm that I have received, read, understood, and agreed to abide by the terms set forth in [DOCUMENT_NAME_REFERENCED] dated [DOCUMENT_DATE].',
        status: 'BBH Standard',
        isMandatory: true,
      },
    ],
  },
];
